Resources:
  CognitoDynamoAccessRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /genki_vn_api/cognitoDynamo/
      RoleName: CognitoDynamoAccessRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: cognitoDynamoAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
              - Effect: Allow
                Action:
                  - cognito-idp:AdminAddUserToGroup
                  - cognito-idp:AdminRemoveUserFromGroup
                  - cognito-idp:ListUsersInGroup
                  - cognito-idp:AdminDeleteUser
                Resource: 'arn:aws:cognito-idp:us-west-2:518872580259:userpool/us-west-2_WV9ZxGPoJ'
              - Effect: Allow
                Action:
                  - dynamodb:DeleteItem
                Resource: "arn:aws:dynamodb:us-west-2:518872580259:table/*"
