service: genki-vn-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminAddUserToGroup
        - cognito-idp:AdminRemoveUserFromGroup
      Resource: 'arn:aws:cognito-idp:us-west-2:132323314018:userpool/us-west-2_WV9ZxGPoJ'

functions:
  addUserToGroup:
    handler: addUserToGroup.main
    events:
      - http:
          path: group
          method: post
          cors: true
          authorizer: aws_iam
  createVirtualClass:
    handler: createVirtualClass.main
    events:
      - http:
          path: createVirtualClass
          method: post
          cors: true
          authorizer: aws_iam
  announcement:
    handler: announcement.main
    events:
      - http:
          path: announcement
          method: post
          cors: true
          authroize: aws_iam
# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
